-- DDL (Data Defintion Languale - CREATE, ALTER, DROP)
-- ALTER (오라클 객체)
-- ALTER를 이용한 제약조건 추가, 수정, 이름변경 해보기! (객체의 수정)
-- +컬럼추가, 컬럼 수정, 컬럼 삭제도 가능함
--**CONSTRAINT TYPE
-- P : PRIMARY KEY
-- R : FOREIGN KEY
-- C : CHECK OR NOT NULL
-- U : UNIQUE
CREATE TABLE USER_FOREIGNKEY_COPY
AS SELECT * FROM USER_FOREIGNKEY;
SELECT * FROM USER_FOREIGNKEY_COPY;
DESC USER_FOREIGNKEY_COPY;

-- 테이블에 컬럼 추가 
ALTER TABLE USER_FOREIGNKEY_COPY
ADD USER_DATE DATE;

-- 테이블에 컬럼 삭제
ALTER TABLE USER_FOREIGNKEY_COPY
DROP COLUMN USER_DATE;
DESC USER_FOREIGNKEY_COPY;

-- 테이블에 컬럼 추가(USER_POINT VARCHAR2(10))
ALTER TABLE USER_FOREIGNKEY_COPY
ADD USER_POINT VARCHAR2(10);
DESC USER_FOREIGNKEY_COPY;

-- 테이블 컬럼 수정
ALTER TABLE USER_FOREIGNKEY_COPY
MODIFY USER_POINT NUMBER;

-- 제약조건 추가, 삭제, 수정, 이름변경
DROP TABLE SHOP_BUY;
DROP TABLE SHOP_MEMBER;

CREATE TABLE SHOP_MEMBER(
    USER_NO NUMBER, --UNIQUE
    USER_ID VARCHAR2(20), --PRIMARY KEY
    USER_PWD VARCHAR2(30), --NOT NULL
    USER_NAME VARCHAR2(30),
    USER_GEDNER CHAR(1),
    USER_PHONE VARCHAR2(20),
    USER_EMAIL VARCHAR2(30)
);

INSERT INTO SHOP_MEMBER VALUES(1, 'khuser01', 'pass01', '일용자', 'M', '01082736744', 'khuser01@naver.com');
SELECT * FROM SHOP_MEMBER;
ROLLBACK;

-- 제약 조건 추가
-- UNIQUE 추가
ALTER TABLE SHOP_MEMBER
ADD CONSTRAINT UNQ_USER_NO UNIQUE(USER_NO); 
-- PRIMARY KEY 추가
ALTER TABLE SHOP_MEMBER
ADD CONSTRAINT PK_USER_ID PRIMARY KEY(USER_ID); 
-- NOT NULL 추가
ALTER TABLE SHOP_MEMBER
MODIFY USER_PWD NOT NULL;
-- 제약조건 삭제
ALTER TABLE SHOP_MEMBER
DROP CONSTRAINT SYS_C007089;
-- 제약 조건 수정 (삭제 후 추가)

------------------------------------------------ 제약조건 확인------------------------------------------------
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'SHOP_MEMBER';
--**CONSTRAINT TYPE
-- P : PRIMARY KEY
-- R : FOREIGN KEY
-- C : CHECK OR NOT NULL
-- U : UNIQUE


CREATE TABLE SHOP_BUY(
    BUY_NO NUMBER, -- P
    USER_ID VARCHAR2(20), -- R(외래키)
    PRODUCT_NAME VARCHAR2(50),
    REG_DATE DATE -- DEFAULT SYSDATE
);

-- 제약 조건 추가
-- PRIMARY KEY를 BUY_NO에 추가
ALTER TABLE SHOP_BUY
ADD CONSTRAINT PK_BUY_NO PRIMARY KEY(BUY_NO);
-- FOREIGN KEY를 USER_ID에 추가
ALTER TABLE SHOP_BUY
ADD CONSTRAINT FK_USER_ID FOREIGN KEY(USER_ID) REFERENCES SHOP_MEMBER(USER_ID);
-- DEFAULT를 REG_DATE (GUI로 확인)
ALTER TABLE SHOP_BUY
MODIFY REG_DATE DEFAULT SYSDATE;

SELECT * FROM SHOP_BUY;
------------------------------------------------ 제약조건 확인------------------------------------------------
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'SHOP_BUY';

-- 제약조건 활성화 / 비활성화
ALTER TABLE SHOP_BUY DISABLE CONSTRAINT FK_USER_ID;
ALTER TABLE SHOP_BUY ENABLE CONSTRAINT FK_USER_ID;

-- 제약조건명 변경
ALTER TABLE SHOP_BUY
RENAME CONSTRAINT PK_BUY_NO TO BUY_NO_PK;

-- 컬럼명 변경
ALTER TABLE SHOP_BUY
RENAME COLUMN REG_DATE TO BUY_DATE;

--테이블명 변경
ALTER TABLE SHOP_BUY RENAME TO SHOP_BUY_TBL;
RENAME SHOP_BUY_TBL TO SHOP_BUY;

DESC SHOP_BUY;















