SELECT * FROM TB_CLASS;
SELECT * FROM TB_PROFESSOR;

-- BASIC SELECT
--   1,6)김현우
--   2,7)권태우
--   3,8)한창희
--   4,9)강정대
--   5,10)이기진
--   

--1)
SELECT DEPARTMENT_NAME AS "학과 명",CATEGORY AS 계열 FROM TB_DEPARTMENT
GROUP BY DEPARTMENT_NAME ,CATEGORY ORDER BY 2;
--2)

--3) 
SELECT STUDENT_NAME , DEPARTMENT_NO, STUDENT_SSN, ABSENCE_YN 
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '001' -- DEPARTMENT_NO가 001 인 쿼리
AND STUDENT_SSN LIKE '%-2%' -- 앞뒤에 무슨 글자가 오던지 -2 이라는 문자가 있는 것을 출력
AND ABSENCE_YN = 'Y'; -- ABSENCE_YN이 Y일때

--4)

--5)

--6)
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

--7)

--8) 
SELECT CLASS_NO as CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

--9)

--10)





