show user;
CREATE USER KHUSER01 IDENTIFIED BY KHUSER01;
SELECT username FROM ALL_USERS;
SELECT USERNAME, ACCOUNT_STATUS, LOCK_DATE FROM DBA_USERS;

GRANT CONNECT TO KHUSER01;
GRANT RESOURCE TO KHUSER01;

CREATE USER KHUSER01 IDENTIFIED BY KHUSER01;
GRANT CONNECT, RESOURCE TO KHUSER01;