-- 제약조건 실습
-- 테이블 생성(DDL - CREATE, ALTER, DROP)
CREATE TABLE USER_NO_CONSTRAINT (
  USER_NO NUMBER,
  USER_ID VARCHAR2(20), -- 한글로 몇글자? 6글자
  USER_PWD VARCHAR2(30),
  USER_NAME VARCHAR2(30), -- 한글 10글자
  USER_GENDER VARCHAR2(10),
  USER_PHONE VARCHAR2(30),
  USER_EMAIL VARCHAR2(50)
);

-- 데이터 추가
INSERT INTO USER_NO_CONSTRAINT VALUES(1, 'khuser01', 'pass01','일용자','남','01098774090','khuser01@iei.or.kr');
-- 데이터 조회
SELECT * FROM USER_NO_CONSTRAINT;
COMMIT; -- TCL(Transaction Control Language)
INSERT INTO USER_NO_CONSTRAINT VALUES(2, 'khuser02', 'pass02','이용자','남','01098774090','khuser01@iei.or.kr');
INSERT INTO USER_NO_CONSTRAINT VALUES(3, null, null, null,'남','01098774090','khuser01@iei.or.kr');

-- 테이블 생성(DDL - CREATE, ALTER, DROP)
CREATE TABLE USER_CONSTRAINT (
  USER_NO NUMBER,
  USER_ID VARCHAR2(20) NOT NULL, -- 한글로 몇글자? 6글자
  USER_PWD VARCHAR2(30) NOT NULL,
  USER_NAME VARCHAR2(30) NOT NULL, -- 한글 10글자
  USER_GENDER VARCHAR2(10),
  USER_PHONE VARCHAR2(30),
  USER_EMAIL VARCHAR2(50)
);
-- 데이터 조회
SELECT * FROM USER_CONSTRAINT;
-- 데이터 추가
INSERT INTO USER_CONSTRAINT VALUES(1,'khuser01', 'pass01','일용자','남','01098774090','khuser01@naver.com');
INSERT INTO USER_CONSTRAINT VALUES(2, null, null, null,'남','01098774090','khuser01@naver.com');

-- USER_NO_CONSTRAINT에 데이터 조회
SELECT * FROM USER_NO_CONSTRAINT;
-- ORA-00942: table or view does not exist -> 테이블명오타
-- ORA-00904 : "USER_PW": invalid indentifier
-- 데이터 추가 (DML - INSERT, UPDATE, DELETE, SELECT)
INSERT INTO USER_NO_CONSTRAINT VALUES(2, 'khuser02', 'pass02','이용자','남','01098774090','khuser02@nate.com');
-- nateimld6@nate.com : 선생님이메일

CREATE TABLE USER_UNIQUE (
  USER_NO NUMBER,
  USER_ID VARCHAR2(20) UNIQUE, -- 한글로 몇글자? 6글자
  USER_PWD VARCHAR2(30) NOT NULL,
  USER_NAME VARCHAR2(30) NOT NULL, -- 한글 10글자
  USER_GENDER VARCHAR2(10),
  USER_PHONE VARCHAR2(30),
  USER_EMAIL VARCHAR2(50)
);
-- 데이터 추가 (INSERT INTO)
INSERT INTO USER_UNIQUE VALUES(1, 'khuser01','pass01','일용자','남','01098774090','khuser01@kakao.com');
-- 데이터조회
SELECT * FROM USER_UNIQUE;

-- 테이블 생성
CREATE TABLE USER_PRIMARYKEY (
  USER_NO NUMBER,
  USER_ID VARCHAR2(20) CONSTRAINT USER_ID_PRIMARY_KEY PRIMARY KEY, -- 한글로 몇글자? 6글자
  USER_PWD VARCHAR2(30) NOT NULL,
  USER_NAME VARCHAR2(30) NOT NULL, -- 한글 10글자
  USER_GENDER VARCHAR2(10),
  USER_PHONE VARCHAR2(30),
  USER_EMAIL VARCHAR2(50)
);
--테이블삭제
DROP TABLE USER_PRIMARYKEY;
--데이터추가
INSERT INTO USER_PRIMARYKEY VALUES(2, 'khuser01','pass01','일용자','남','01098774090','khuser01@kh.com');
--ORA-00001: unique constraint (KHUSER01.SYS_C007008) violated
--데이터조회
SELECT * FROM USER_PRIMARYKEY;

-- CHECK 제약조건
-- ORA-02264: name already used by an existing constraint
CREATE TABLE USER_CHECK (
  USER_NO NUMBER,
  USER_ID VARCHAR2(20) CONSTRAINT UID_PRIMARY_KEY PRIMARY KEY, -- 한글로 몇글자? 6글자
  USER_PWD VARCHAR2(30) NOT NULL,
  USER_NAME VARCHAR2(30) NOT NULL, -- 한글 10글자
  USER_GENDER VARCHAR2(10) CHECK(USER_GENDER IN('M', 'F')),
  USER_PHONE VARCHAR2(30),
  USER_EMAIL VARCHAR2(50)
);

-- 데이터 추가
INSERT INTO USER_CHECK VALUES(1, 'khuser01', 'pass01', '일용자', 'M', '01028279383','khuser01@kh.com');
-- ORA-02290: check constraint (KHUSER01.SYS_C007020) violated
-- 데이터 조회
SELECT * FROM USER_CHECK;
COMMIT;


-- DEFAULT 제약조건
CREATE TABLE USER_DEFAULT (
  USER_NO NUMBER,
  USER_ID VARCHAR2(20) PRIMARY KEY, -- 한글로 몇글자? 6글자
  USER_PWD VARCHAR2(30) NOT NULL,
  USER_NAME VARCHAR2(30) NOT NULL, -- 한글 10글자
  USER_GENDER VARCHAR2(10) CHECK(USER_GENDER IN('M', 'F')),
  USER_PHONE VARCHAR2(30),
  USER_EMAIL VARCHAR2(50),
  USER_DATE DATE DEFAULT SYSDATE
);

-- 테이블 삭제
DROP TABLE USER_DEFAULT;

-- 데이터 추가
INSERT INTO USER_DEFAULT VALUES(1, 'khuser01', 'pass01','일용자','M','01082729383','khuser01@kh.com', DEFAULT);
-- 데이터 조회
SELECT * FROM USER_DEFAULT;
DELETE FROM USER_DEFAULT;

INSERT INTO USER_DEFAULT VALUES(2, 'khuser02', 'pass02','이용자','M','01082729383','khuser02@kh.com', SYSDATE);

-- FOREIGN KEY 제약조건
-- 테이블 추가
CREATE TABLE USER_GRADE (
  GRADE_CODE NUMBER PRIMARY KEY,
  GRADE_NAME VARCHAR2(30) NOT NULL
);

-- 데이터추가
INSERT INTO USER_GRADE VALUES(10, '우수회원');
INSERT INTO USER_GRADE VALUES(20, '우수회원');
INSERT INTO USER_GRADE VALUES(30, '특별회원');
INSERT INTO USER_GRADE VALUES(40, 'VIP 회원');
COMMIT;
-- 부모 테이블의 데이터를 삭제하려고 할 때 못지운다.
DELETE FROM USER_GRADE WHERE GRADE_CODE = 40;

-- 참조하는 테이블, 자식테이블
CREATE TABLE USER_FOREIGNKEY (
  USER_NO NUMBER PRIMARY KEY,
  USER_ID VARCHAR2(20) UNIQUE,
  USER_PWD VARCHAR2(30) NOT NULL,
  USER_NAME VARCHAR2(30),
  USER_GENDER VARCHAR2(10),
  USER_PHONE VARCHAR2(30),
  USER_EMAIL VARCHAR2(50),
  GRADE_CODE NUMBER REFERENCES USER_GRADE(GRADE_CODE)
  --FOREIGN KEY(GRADE_CODE) REFERENCES USER_GRADE(GRADE_CODE)
);

DROP TABLE USER_GRADE;
DROP TABLE USER_FOREIGNKEY;

-- 데이터 추가
INSERT INTO USER_FOREIGNKEY VALUES(1, 'khuser01', 'pass01','일용자','남','01082729282', 'khuser@kh.com', 10);
-- 데이터 조회
SELECT * FROM USER_FOREIGNKEY;
INSERT INTO USER_FOREIGNKEY VALUES(2, 'khuser02', 'pass02','이용자','남','01082729282', 'khuser@kh.com', 20);
INSERT INTO USER_FOREIGNKEY VALUES(3, 'khuser03', 'pass03','삼용자','남','01082729282', 'khuser@kh.com', 30);
INSERT INTO USER_FOREIGNKEY VALUES(4, 'khuser04', 'pass04','사용자','남','01082729282', 'khuser@kh.com', 40);
--ORA-02291: integrity constraint (KHUSER01.SYS_C007046) violated - parent key not found
COMMIT;

-- 자식을 지우고 부모를 지우면 지워짐
DELETE FROM USER_FOREIGNKEY WHERE GRADE_CODE = 40;
DELETE FROM USER_GRADE WHERE GRADE_CODE = 40;
ROLLBACK;

-- 삭제옵션
-- 기본 옵션 ON DELETE RESTRICTED(삭제가제한된다)
-- 연관된 모든 것 삭제 옵션 ON DELETE CASCADE
-- NULL로 만드는 옵션 ON DELETE SET NULL
-- 이 옵션을 외래키 설정시에 같이 적어주어야 적용됨

CREATE TABLE USER_FOREIGNKEY (
  USER_NO NUMBER PRIMARY KEY,
  USER_ID VARCHAR2(20) UNIQUE,
  USER_PWD VARCHAR2(30) NOT NULL,
  USER_NAME VARCHAR2(30),
  USER_GENDER VARCHAR2(10),
  USER_PHONE VARCHAR2(30),
  USER_EMAIL VARCHAR2(50),
  GRADE_CODE NUMBER REFERENCES USER_GRADE(GRADE_CODE) ON DELETE SET NULL
  --FOREIGN KEY(GRADE_CODE) REFERENCES USER_GRADE(GRADE_CODE)
);

DROP TABLE USER_GRADE;
DROP TABLE USER_FOREIGNKEY;
-- ON DELETE CASCADE 테스트
SELECT * FROM USER_FOREIGNKEY;
SELECT * FROM USER_GRADE;
DELETE FROM USER_GRADE WHERE GRADE_CODE = 40;
-- ON DELETE SET NULL 테스트
DELETE FROM USER_GRADE WHERE GRADE_CODE = 40;
COMMIT;

-- 세줄 요약
-- 1.왜래키(자식테이블)가 참조하는 부모테이블 컬럼 데이터는 기본적으로 지워지지 않음.
-- 2.ON DELETE CASCADE 옵션은 부모테이블 데이터를 지워주고 자식테이블 데이터도 지워줌.
-- 3.ON DELETE SET NULL 옵션은 부모테이블 데이터를 지워주고 자식테이블 데이터는 NULL로 해줌

-- SHOP 고객 테이블
CREATE TABLE SHOP_MEMBER( --부모
  USER_NO NUMBER UNIQUE,
  USER_ID VARCHAR2(20) PRIMARY KEY,
  USER_PWD VARCHAR2(30) NOT NULL,
  USER_NAME VARCHAR2(30),
  USER_GENDER CHAR(1),
  USER_PHONE VARCHAR2(20),
  USER_EMAIL VARCHAR2(30)
);

INSERT INTO SHOP_MEMBER VALUES(1, 'khuser01', 'pass01', '일용자' , 'M', '01082729333', 'khuser01@kh.com');
INSERT INTO SHOP_MEMBER VALUES(2, 'khuser02', 'pass02', '일용자' , 'M', '01082724333', 'khuser01@kh.com');
INSERT INTO SHOP_MEMBER VALUES(3, 'khuser03', 'pass03', '일용자' , 'M', '01082725333', 'khuser01@kh.com');
INSERT INTO SHOP_MEMBER VALUES(4, 'khuser04', 'pass04', '일용자' , 'M', '01082728333', 'khuser01@kh.com');

-- SHOP 구매 내역 테이블
CREATE TABLE SHOP_BUY( -- 자식
  BUY_NO NUMBER PRIMARY KEY,
  USER_ID VARCHAR2(30) REFERENCES SHOP_MEMBER(USER_ID),
  PRODUCT_NAME VARCHAR2(20),
  REG_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM SHOP_MEMBER;
DESC SHOP_BUY;
INSERT INTO SHOP_BUY VALUES(1, 'khuser01', '농구화', DEFAULT);
INSERT INTO SHOP_BUY VALUES(2, 'khuser02', '농구화', DEFAULT);
INSERT INTO SHOP_BUY VALUES(3, 'khuser03', '농구화', DEFAULT);
INSERT INTO SHOP_BUY VALUES(4, 'khuser04', '농구화', DEFAULT);
--INSERT INTO SHOP_BUY VALUES(5, 'khuser05', '농구화', DEFAULT);
SELECT * FROM SHOP_BUY;
COMMIT;
DELETE FROM SHOP_MEMBER WHERE USER_NO = 1;
DROP TABLE SHOP_BUY;

-- SHOP 구매 내역 테이블
CREATE TABLE SHOP_BUY( -- 자식
  BUY_NO NUMBER PRIMARY KEY,
  USER_ID VARCHAR2(30) REFERENCES SHOP_MEMBER(USER_ID) ON DELETE SET NULL,
  PRODUCT_NAME VARCHAR2(20),
  REG_DATE DATE DEFAULT SYSDATE
);

DELETE FROM SHOP_MEMBER WHERE USER_NO = 1;
SELECT * FROM SHOP_BUY;
COMMIT;
