-- 제약조건 실습
-- 테이블 생성(DDL - CREATE, ALTER, DROP)
CREATE TABLE USER_NO_CONSTRAINT (
  USER_NO NUMBER,
  USER_ID VARCHAR2(20), -- 한글로 몇글자? 6글자
  USER_PWD VARCHAR2(30),
  USER_NAME VARCHAR2(30), -- 한글 10글자
  USER_GENDER VARCHAR2(10),
  USER_PHONE VARCHAR2(30),
  USER_EMAIL VARCHAR2(50)
);

-- 데이터 추가
INSERT INTO USER_NO_CONSTRAINT VALUES(1, 'khuser01', 'pass01','일용자','남','01098774090','khuser01@iei.or.kr');
-- 데이터 조회
SELECT * FROM USER_NO_CONSTRAINT;
COMMIT; -- TCL(Transaction Control Language)
INSERT INTO USER_NO_CONSTRAINT VALUES(2, 'khuser02', 'pass02','이용자','남','01098774090','khuser01@iei.or.kr');
INSERT INTO USER_NO_CONSTRAINT VALUES(3, null, null, null,'남','01098774090','khuser01@iei.or.kr');

-- 테이블 생성(DDL - CREATE, ALTER, DROP)
CREATE TABLE USER_CONSTRAINT (
  USER_NO NUMBER,
  USER_ID VARCHAR2(20) NOT NULL, -- 한글로 몇글자? 6글자
  USER_PWD VARCHAR2(30) NOT NULL,
  USER_NAME VARCHAR2(30) NOT NULL, -- 한글 10글자
  USER_GENDER VARCHAR2(10),
  USER_PHONE VARCHAR2(30),
  USER_EMAIL VARCHAR2(50)
);
-- 데이터 조회
SELECT * FROM USER_CONSTRAINT;
-- 데이터 추가
INSERT INTO USER_CONSTRAINT VALUES(1,'khuser01', 'pass01','일용자','남','01098774090','khuser01@naver.com');
INSERT INTO USER_CONSTRAINT VALUES(2, null, null, null,'남','01098774090','khuser01@naver.com');

-- USER_NO_CONSTRAINT에 데이터 조회
SELECT * FROM USER_NO_CONSTRAINT;
-- ORA-00942: table or view does not exist -> 테이블명오타
-- ORA-00904 : "USER_PW": invalid indentifier
-- 데이터 추가 (DML - INSERT, UPDATE, DELETE, SELECT)
INSERT INTO USER_NO_CONSTRAINT VALUES(2, 'khuser02', 'pass02','이용자','남','01098774090','khuser02@nate.com');
-- nateimld6@nate.com : 선생님이메일

CREATE TABLE USER_UNIQUE (
  USER_NO NUMBER,
  USER_ID VARCHAR2(20) UNIQUE, -- 한글로 몇글자? 6글자
  USER_PWD VARCHAR2(30) NOT NULL,
  USER_NAME VARCHAR2(30) NOT NULL, -- 한글 10글자
  USER_GENDER VARCHAR2(10),
  USER_PHONE VARCHAR2(30),
  USER_EMAIL VARCHAR2(50)
);
-- 데이터 추가 (INSERT INTO)
INSERT INTO USER_UNIQUE VALUES(1, 'khuser01','pass01','일용자','남','01098774090','khuser01@kakao.com');
-- 데이터조회
SELECT * FROM USER_UNIQUE;

-- 테이블 생성
CREATE TABLE USER_PRIMARYKEY (
  USER_NO NUMBER,
  USER_ID VARCHAR2(20) CONSTRAINT USER_ID_PRIMARY_KEY PRIMARY KEY, -- 한글로 몇글자? 6글자
  USER_PWD VARCHAR2(30) NOT NULL,
  USER_NAME VARCHAR2(30) NOT NULL, -- 한글 10글자
  USER_GENDER VARCHAR2(10),
  USER_PHONE VARCHAR2(30),
  USER_EMAIL VARCHAR2(50)
);
--테이블삭제
DROP TABLE USER_PRIMARYKEY;
--데이터추가
INSERT INTO USER_PRIMARYKEY VALUES(2, 'khuser01','pass01','일용자','남','01098774090','khuser01@kh.com');
--ORA-00001: unique constraint (KHUSER01.SYS_C007008) violated
--데이터조회
SELECT * FROM USER_PRIMARYKEY;

-- CHECK 제약조건
-- ORA-02264: name already used by an existing constraint
CREATE TABLE USER_CHECK (
  USER_NO NUMBER,
  USER_ID VARCHAR2(20) CONSTRAINT UID_PRIMARY_KEY PRIMARY KEY, -- 한글로 몇글자? 6글자
  USER_PWD VARCHAR2(30) NOT NULL,
  USER_NAME VARCHAR2(30) NOT NULL, -- 한글 10글자
  USER_GENDER VARCHAR2(10) CHECK(USER_GENDER IN('M', 'F')),
  USER_PHONE VARCHAR2(30),
  USER_EMAIL VARCHAR2(50)
);

-- 데이터 추가
INSERT INTO USER_CHECK VALUES(1, 'khuser01', 'pass01', '일용자', 'M', '01028279383','khuser01@kh.com');
-- ORA-02290: check constraint (KHUSER01.SYS_C007020) violated
-- 데이터 조회
SELECT * FROM USER_CHECK;
COMMIT;


-- DEFAULT 제약조건
CREATE TABLE USER_DEFAULT (
  USER_NO NUMBER,
  USER_ID VARCHAR2(20) PRIMARY KEY, -- 한글로 몇글자? 6글자
  USER_PWD VARCHAR2(30) NOT NULL,
  USER_NAME VARCHAR2(30) NOT NULL, -- 한글 10글자
  USER_GENDER VARCHAR2(10) CHECK(USER_GENDER IN('M', 'F')),
  USER_PHONE VARCHAR2(30),
  USER_EMAIL VARCHAR2(50),
  USER_DATE DATE DEFAULT SYSDATE
);

-- 테이블 삭제
DROP TABLE USER_DEFAULT;

-- 데이터 추가
INSERT INTO USER_DEFAULT VALUES(1, 'khuser01', 'pass01','일용자','M','01082729383','khuser01@kh.com', DEFAULT);
-- 데이터 조회
SELECT * FROM USER_DEFAULT;
DELETE FROM USER_DEFAULT;

INSERT INTO USER_DEFAULT VALUES(2, 'khuser02', 'pass02','이용자','M','01082729383','khuser02@kh.com', SYSDATE);

-- FOREIGN KEY 제약조건
-- 테이블 추가
CREATE TABLE USER_GRADE (
  GRADE_CODE NUMBER PRIMARY KEY,
  GRADE_NAME VARCHAR2(30) NOT NULL
);

-- 데이터추가
INSERT INTO USER_GRADE VALUES(10, '우수회원');
INSERT INTO USER_GRADE VALUES(20, '우수회원');
INSERT INTO USER_GRADE VALUES(30, '특별회원');
INSERT INTO USER_GRADE VALUES(40, 'VIP 회원');
COMMIT;
-- 부모 테이블의 데이터를 삭제하려고 할 때 못지운다.
DELETE FROM USER_GRADE WHERE GRADE_CODE = 40;

-- 참조하는 테이블, 자식테이블
CREATE TABLE USER_FOREIGNKEY (
  USER_NO NUMBER PRIMARY KEY,
  USER_ID VARCHAR2(20) UNIQUE,
  USER_PWD VARCHAR2(30) NOT NULL,
  USER_NAME VARCHAR2(30),
  USER_GENDER VARCHAR2(10),
  USER_PHONE VARCHAR2(30),
  USER_EMAIL VARCHAR2(50),
  GRADE_CODE NUMBER REFERENCES USER_GRADE(GRADE_CODE)
  --FOREIGN KEY(GRADE_CODE) REFERENCES USER_GRADE(GRADE_CODE)
);

DROP TABLE USER_GRADE;
DROP TABLE USER_FOREIGNKEY;

-- 데이터 추가
INSERT INTO USER_FOREIGNKEY VALUES(1, 'khuser01', 'pass01','일용자','남','01082729282', 'khuser@kh.com', 10);
-- 데이터 조회
SELECT * FROM USER_FOREIGNKEY;
INSERT INTO USER_FOREIGNKEY VALUES(2, 'khuser02', 'pass02','이용자','남','01082729282', 'khuser@kh.com', 20);
INSERT INTO USER_FOREIGNKEY VALUES(3, 'khuser03', 'pass03','삼용자','남','01082729282', 'khuser@kh.com', 30);
INSERT INTO USER_FOREIGNKEY VALUES(4, 'khuser04', 'pass04','사용자','남','01082729282', 'khuser@kh.com', 40);
--ORA-02291: integrity constraint (KHUSER01.SYS_C007046) violated - parent key not found
COMMIT;







