CREATE TABLE HUMAN_INFO(
  NAME VARCHAR2(50) PRIMARY KEY,
  AGE NUMBER NOT NULL,
  ADDRESS VARCHAR2(50),
  PHONE VARCHAR2(50) UNIQUE,
  CHECK_CAR VARCHAR2(10) CHECK(CHECK_CAR IN('Y','N')),
  REG_DATE DATE
);

SELECT * FROM HUMAN_INFO;
DROP TABLE HUMAN_INFO;

INSERT INTO HUMAN_INFO VALUES('한창희', 31, '서울시 서대문구' ,010-9877-4090, 'N', SYSDATE);
INSERT INTO HUMAN_INFO VALUES('정재훈', 31, '안양시 동안구', 010-9877-4091, 'N', SYSDATE);
INSERT INTO HUMAN_INFO VALUES('이동환', 31, '안양시 금정구', 010-9877-4092, 'Y', SYSDATE);
INSERT INTO HUMAN_INFO VALUES('남지현', 31, '안양시 동안구', 010-9877-4093, 'N', SYSDATE);
INSERT INTO HUMAN_INFO VALUES('김관희', 32, '수원시 조원구', 010-9877-4094, 'Y', SYSDATE);

-- NOT NULL 제약조건 AGE이가 NOT NULL이라 삽입불가
INSERT INTO HUMAN_INFO VALUES('조인성',null,'안양시 동안구', 010-9877-4095,'Y',SYSDATE); 

-- UNIQUE 제약조건 (중복된 값 허용하지않음)
INSERT INTO HUMAN_INFO VALUES('권상우',40,'서울시 중구', 010-9877-4090, 'Y', SYSDATE);

-- PRIMARY KEY (테이블당 하나 설정 가능 NOT NULL+UNIQUE 합친속성)
INSERT INTO HUMAN_INFO VALUES('한창희',32,'서울시 서대문구',010-9877-4090,'N',SYSDATE);

-- CHECK 제약조건 (데이터 값의 범위나 조건을 지정해 설정한값 허용)
SELECT CHECK_CAR FROM HUMAN_INFO;

-- DEFAULT 제약조건 (기본값으로 설정한 값이 자동으로 입력되도록 하는 제약조건)
CREATE TABLE USER_DEFAULT (
  USER_NO NUMBER,
  USER_ID VARCHAR2(20) PRIMARY KEY, 
  USER_PWD VARCHAR2(30) NOT NULL,
  USER_NAME VARCHAR2(30) NOT NULL,
  USER_GENDER VARCHAR2(10) CHECK(USER_GENDER IN('M', 'F')),
  USER_PHONE VARCHAR2(30),
  USER_EMAIL VARCHAR2(50),
  USER_DATE DATE DEFAULT SYSDATE
);
INSERT INTO USER_DEFAULT VALUES(1, 'khuser01', 'pass01','일용자','M','01082729383','khuser01@kh.com', DEFAULT);
INSERT INTO USER_DEFAULT VALUES(2, 'khuser02', 'pass02','이용자','M','01082729383','khuser02@kh.com', SYSDATE);
SELECT * FROM USER_DEFAULT;

-- FOREIGN KEY 제약조건 (참조되는 테이블의 컬럼의값이 존재하면 허용한다. 따로테이블만들어서 본다.)
-- ON DELETE CASCADE : PARENT 삭제 시 CHILD 같이 삭제
-- ON DELETE SET NULL: PARENT 삭제 시 CHILD의 해당 필드 NULL로 업데이트
-- ON DELETE SET DEFAULT : PARENT 삭제 시 CHILD의 해당 필드 DEFAULT 값으로 UPDATE
-- ON DELETE RESTRICTED : CHILD 테이블에 PK 값이 없는 경우만 PARENT 삭제 --(기본삭제옵션)
-- ON DELETE NO ACTION : 참조 무결성 제약조건을 위배하는 액션은 불가

CREATE TABLE USER_GRADE(
  GRADE_CODE NUMBER PRIMARY KEY,
  GRADE_NAME VARCHAR2(30) NOT NULL
);

-- USER_GRADE 데이터추가
INSERT INTO USER_GRADE VALUES(10, '우수회원');
INSERT INTO USER_GRADE VALUES(20, '우수회원');
INSERT INTO USER_GRADE VALUES(30, '특별회원');
INSERT INTO USER_GRADE VALUES(40, 'VIP 회원');

CREATE TABLE USER_FOREIGNKEY (
  USER_NO NUMBER PRIMARY KEY,
  USER_ID VARCHAR2(20) UNIQUE,
  USER_PWD VARCHAR2(30) NOT NULL,
  USER_NAME VARCHAR2(30),
  USER_GENDER VARCHAR2(10),
  USER_PHONE VARCHAR2(30),
  USER_EMAIL VARCHAR2(50),
  GRADE_CODE NUMBER REFERENCES USER_GRADE(GRADE_CODE) --테이블레벨설정
  --FOREIGN KEY(GRADE_CODE) REFERENCES USER_GRADE(GRADE_CODE) -- 컬럼 레벨설정
);

SELECT * FROM USER_GRADE;
SELECT * FROM USER_FOREIGNKEY;

-- USER_FOREIGNKEY 데이터추가
INSERT INTO USER_FOREIGNKEY VALUES(1, 'khuser01', 'pass01','일용자','남','01082729282', 'khuser@kh.com', 10);
INSERT INTO USER_FOREIGNKEY VALUES(2, 'khuser02', 'pass02','이용자','남','01082729282', 'khuser@kh.com', 20);
INSERT INTO USER_FOREIGNKEY VALUES(3, 'khuser03', 'pass03','삼용자','남','01082729282', 'khuser@kh.com', 30);
INSERT INTO USER_FOREIGNKEY VALUES(4, 'khuser04', 'pass04','사용자','남','01082729282', 'khuser@kh.com', 40);

-- 자식을 지우고 부모를 지우면 지워짐
DELETE FROM USER_GRADE WHERE GRADE_CODE = 40;
DELETE FROM USER_FOREIGNKEY WHERE GRADE_CODE = 40;
ROLLBACK;

-- 세줄 요약
-- 1.왜래키(자식테이블)가 참조하는 부모테이블 컬럼 데이터는 기본적으로 지워지지 않음.
-- 2.ON DELETE CASCADE 옵션은 부모테이블 데이터를 지워주고 자식테이블 데이터도 지워줌.
-- 3.ON DELETE SET NULL 옵션은 부모테이블 데이터를 지워주고 자식테이블 데이터는 NULL로 해줌


DROP TABLE USER_GRADE;
DROP TABLE USER_FOREIGNKEY;

















