SELECT * FROM IDOL_GROUP;
SELECT * FROM IDOL_MEMBER;

-- 그룹에는 15개의 IDOL_GROUP이 있는데 MEMBER에는 4개만 있었다. 
-- 그래서 JOIN을 한 결과 4개의 GROUP밖에 보이지 않음. 이런방식을 INNER JOIN
-- INNER JOIN은 A 테이블과 B테이블에 모두 존재하는 데이터들만 나온다.
-- 그래서 둘중에 한 테이블에라도 존재하지 않는다면 나오지가않는다.
SELECT A.COMPANY, A.GROUP_NAME, B.MEMBER_NAME, B.REAL_NAME 
FROM IDOL_GROUP A, IDOL_MEMBER B WHERE A.GROUP_NAME = B.GROUP_NAME;

-- COUNT를 쓸 때는 GROUP BY를 써야된다.
SELECT A.COMPANY, A.GROUP_NAME, COUNT(B.MEMBER_NAME) COUNT 
FROM IDOL_GROUP A, IDOL_MEMBER B WHERE A.GROUP_NAME = B.GROUP_NAME GROUP BY A.COMPANY, A.GROUP_NAME;












