CREATE TABLE INFO(
  ID NUMBER,
  NAME VARCHAR2(100),
  BIRTH DATE,
  BTYPE CHAR(2)
);

DESC INFO; --테이블의정보를 보는 것도가능
SELECT * FROM INFO;

INSERT INTO "INFO" VALUES (1, '홍길동', SYSDATE, 'B');
INSERT INTO "INFO" VALUES (2, '이순신', '2020-12-23', 'B');
INSERT INTO "INFO" ("ID", "NAME") VALUES (3, '임꺽정');
INSERT INTO "INFO" ("BTYPE", "NAME") VALUES ('AB', '강감찬');
INSERT INTO "INFO" ("ID", "NAME", "BIRTH", "BTYPE") VALUES (5, '장영실', '2011-01-26', 'O');
INSERT INTO "INFO" VALUES (2, '이순신', '2020-12-23', 'B');

-- 값 수정하기 (SELECT에서 사용하는 WHERE 조건 형태 활용)
UPDATE "INFO" SET "ID"=10 WHERE "ID"=1;
UPDATE "INFO" SET "NAME"='이길동' WHERE "ID"=1;
UPDATE "INFO" SET "NAME"='이길동' WHERE "ID"=10;
UPDATE "INFO" SET "NAME"='홍길동',"BTYPE"='C' WHERE "ID"=10;
UPDATE "INFO" SET "BIRTH"=SYSDATE WHERE "NAME"='강감찬';
UPDATE "INFO" SET "BIRTH"='1988-09-21', "NAME"='김꺽정' WHERE "ID"=3;
UPDATE "INFO" SET "BTYPE"='A' WHERE "ID"=3;
UPDATE "INFO" SET "ID"=100 WHERE "NAME"='강감찬';
COMMIT;
UPDATE "INFO" SET "BTYPE"='O'; /* WHERE절이 없는 경우 모든 행 수정 */
ROLLBACK;

-- 값 삭제하기(SELECT에서 사용하는 WHERE 조건 형태 활용)
DELETE FROM "INFO"; /* WHERE절이 없는 경우 모든 행 삭제 */
ROLLBACK;
SELECT * FROM INFO WHERE ID = 100;
DELETE FROM "INFO" WHERE "ID"=100;
SELECT * FROM "INFO" WHERE "ID"=3 AND "NAME"='홍길동';
DELETE FROM "INFO" WHERE "ID"=3 AND "NAME"='홍길동';
SELECT * FROM "INFO" WHERE "ID"=3 OR "NAME"='%길동';
DELETE FROM "INFO" WHERE "ID"=3 OR "NAME"='%길동';

-- SELECT 사용해보기 --
INSERT INTO "INFO" VALUES (1, '홍길동', SYSDATE, 'B');
INSERT INTO "INFO" VALUES (2, '이순신', '2020-12-23', 'B');
INSERT INTO "INFO" ("ID", "NAME") VALUES (3, '임꺽정');
INSERT INTO "INFO" ("BTYPE", "NAME") VALUES ('AB', '강감찬');
INSERT INTO "INFO" ("ID", "NAME", "BIRTH", "BTYPE") VALUES (5, '장영실', '2011-01-26', 'O');
INSERT INTO "INFO" VALUES (2, '이순신', '2020-12-23', 'B');

-- 값 조회
SELECT * FROM INFO;
SELECT ID, NAME, BIRTH,BTYPE FROM INFO;
SELECT NAME, BIRTH FROM INFO;
SELECT ID NAME FROM INFO;
SELECT NAME, ID FROM INFO;

-- 검색(WHERE)
SELECT "NAME" FROM "INFO" WHERE "ID"=1;
SELECT "NAME" FROM "INFO" WHERE "ID"=3;
SELECT "NAME" FROM "INFO" WHERE "ID"=100;
SELECT * FROM "INFO" WHERE "ID" IS NULL;
SELECT * FROM "INFO" WHERE "BTYPE" IS NULL;
SELECT * FROM "INFO" WHERE "BTYPE" IS NULL AND "BIRTH" IS NULL;
SELECT * FROM "INFO" WHERE "BTYPE" IS NULL OR "BIRTH" IS NULL;
SELECT * FROM "INFO" WHERE "ID" IS NOT NULL;

SELECT "NAME" FROM "INFO" WHERE "ID"=1 AND "NAME"='홍길동';
SELECT "NAME" FROM "INFO" WHERE "ID"=1 AND "NAME"='AB';
SELECT "NAME" FROM "INFO" WHERE "ID"=1 OR "NAME"='홍길동';
SELECT "NAME" FROM "INFO" WHERE "ID"=1 OR "NAME"='AB';
SELECT "NAME" FROM "INFO" WHERE NOT "NAME"='이순신';
SELECT "NAME" FROM "INFO" WHERE "NAME"!='이순신';
SELECT "NAME" FROM "INFO" WHERE "NAME"&lt;&gt;'이순신';

SELECT "NAME" FROM "INFO" WHERE "ID"!=3;
SELECT * FROM "INFO" WHERE "ID" BETWEEN 2 AND 4;
SELECT * FROM "INFO" WHERE "ID"&gt;3;
SELECT * FROM "INFO" WHERE "BIRTH"&lt;'2021-01-01';
SELECT * FROM "INFO" WHERE "BIRTH" BETWEEN '2020-01-01' AND SYSDATE;
SELECT * FROM "INFO" WHERE "ID"&gt;=3;
SELECT * FROM "INFO" WHERE "ID" IN(1,5,2);
SELECT * FROM "INFO" WHERE "ID" NOT IN(1,5,2);
SELECT "NAME" FROM "INFO" WHERE "NAME" LIKE '%길%';
SELECT "NAME" FROM "INFO" WHERE "NAME" LIKE '%홍길%';
SELECT "NAME" FROM "INFO" WHERE "NAME" LIKE '_홍길%';
SELECT "NAME" FROM "INFO" WHERE "NAME" LIKE '_길%';
SELECT "ID"||"NAME" FROM "INFO" WHERE "ID"=1;
SELECT "ID"||"NAME" AS "NAME" FROM "INFO" WHERE "ID"=1;
SELECT DISTINCT * FROM "INFO";

조회결과 정렬하기
SELECT ID, "NAME", "BIRTH" FROM "INFO" ORDER BY "ID";
SELECT "NAME", "BIRTH" FROM "INFO" ORDER BY "BIRTH" ASC;
SELECT "ID", "NAME", "BTYPE" FROM "INFO" ORDER BY "BTYPE";
SELECT "ID", "NAME", "BTYPE" FROM "INFO" ORDER BY "BTYPE", "NAME";
SELECT "ID", "NAME", "BTYPE" FROM "INFO" ORDER BY "BTYPE" DESC, "NAME" DESC;







