CREATE TABLE BRANDS(
  BRAND_ID NUMBER PRIMARY KEY,
  BRAND_NAME VARCHAR2(100) NOT NULL
);

INSERT INTO BRANDS VALUES(SEQ_BRAND_ID.NEXTVAL,'삼성');
INSERT INTO BRANDS VALUES(SEQ_BRAND_ID.NEXTVAL,'애플');

CREATE TABLE PRODUCTS( -- 방법1(컬럼레벨 테이블설정 일단이걸로구현)
  PRODUCT_NO NUMBER PRIMARY KEY,
  PRODUCT_NAME VARCHAR2(20) NOT NULL,
  PRODUCT_PRICE NUMBER NOT NULL,
  BRAND_CODE NUMBER REFERENCES BRANDS(BRAND_ID), -- 1.컬럼레벨 Foreign Key 설정
  SERIAL_NO VARCHAR2(100) UNIQUE,
  SOLD_OUT CHAR(1) DEFAULT 'N' CHECK(SOLD_OUT IN('Y','N'))
);

INSERT INTO PRODUCTS VALUES(SEQ_PRODUCT_NO.NEXTVAL, '갤럭시S8', 800000, 100, 'S8','Y');
INSERT INTO PRODUCTS VALUES(SEQ_PRODUCT_NO.NEXTVAL, '갤럭시S9', 900000, 100, 'S9','N');
INSERT INTO PRODUCTS VALUES(SEQ_PRODUCT_NO.NEXTVAL, '갤럭시S10', 1000000, 100, 'S10','N');
INSERT INTO PRODUCTS VALUES(SEQ_PRODUCT_NO.NEXTVAL, '아이폰9S', 900000, 200, '9S','N');
INSERT INTO PRODUCTS VALUES(SEQ_PRODUCT_NO.NEXTVAL, '아이폰10S', 1000000, 200, '10S','N');

CREATE SEQUENCE SEQ_BRAND_ID -- 100부터 시작하여 100씩 증가, 최대값 1000, 반복 없음.
MINVALUE 100
MAXVALUE 1000
START WITH 100
INCREMENT BY 100
CYCLE
NOCACHE;

SELECT SEQ_BRAND_ID.NEXTVAL FROM DUAL;
SELECT SEQ_BRAND_ID.CURRVAL FROM DUAL;
SELECT SEQ_PRODUCT_NO.CURRVAL FROM DUAL;

CREATE SEQUENCE SEQ_PRODUCT_NO --1부터 시작하여 1씩 증가, 최대값 10000, 반복 없음.
MINVALUE 1
MAXVALUE 10000
START WITH 1
INCREMENT BY 1
CYCLE
NOCACHE;


DROP TABLE BRANDS;
DROP TABLE PRODUCTS;
DROP SEQUENCE SEQ_BRAND_ID;
DROP SEQUENCE SEQ_PRODUCT_NO;


SELECT * FROM BRANDS;
SELECT * FROM PRODUCTS;


-- 테이블조회영역 --
SELECT A.PRODUCT_NAME, A.PRODUCT_PRICE, B.BRAND_NAME, A.SOLD_OUT
FROM PRODUCTS A JOIN BRANDS B ON(A.BRAND_CODE = B.BRAND_ID);


























-- ============== 번외(혼자예시들어서해본거) ==============
CREATE TABLE PRODUCTS2( -- 방법2(테이블레벨 설정해보기 연습)
  PRODUCT_NO NUMBER,
  PRODUCT_NAME VARCHAR2(20) NOT NULL,
  PRODUCT_PRICE NUMBER NOT NULL,
  BRAND_CODE NUMBER,
  SERIAL_NO VARCHAR2(100) UNIQUE,
  SOLD_OUT CHAR(1) DEFAULT 'N' CHECK(SOLD_OUT IN('Y','N')),
  -- PK_PRODUCT_NO 라는 이름으로 PRIMARY KEY 제약조건을 설정한다. PRODUCT_NO 컬럼에다가
  CONSTRAINT PK_PRODUCT_NO PRIMARY KEY(PRODUCT_NO),
  -- FK_BRAND_CODE 라는 이름으로 FOREIGN KEY 제약조건을 설정한다. BRADN_CODE 컬럼에다가
  CONSTRAINT FK_BRAND_CODE FOREIGN KEY(BRAND_CODE) REFERENCES BRANDS(BRAND_ID)
);

CREATE TABLE PRODUCTS3( -- 방법3(테이블 생성 후 추가 연습)
  PRODUCT_NO NUMBER,
  PRODUCT_NAME VARCHAR2(20) NOT NULL,
  PRODUCT_PRICE NUMBER NOT NULL,
  BRAND_CODE NUMBER,
  SERIAL_NO VARCHAR2(100) UNIQUE,
  SOLD_OUT CHAR(1) DEFAULT 'N' CHECK(SOLD_OUT IN('Y','N'))
);
ALTER TABLE PRODUCTS3 ADD CONSTRAINT PRODUCT_NO_PK PRIMARY KEY(PRODUCT_NO);
ALTER TABLE PRODUCTS3 ADD CONSTRAINT BRAND_CODE_FK FOREIGN KEY(BRAND_CODE)
  REFERENCES BRANDS(BRAND_ID);

DROP TABLE PRODUCTS2;
















