-- SEQUENCE (시퀀스)
-- 순차적으로 정수 값을 자동으로 생성하는 객체, 자동번호 발생기(채번기)의 역할을 함.
CREATE SEQUENCE SEQ_USER_NO;
CREATE SEQUENCE SEQ_USER_NO2;

SELECT * FROM SEQUENCE;
-- =============== 시퀀스 옵션 ===============
-- START WITH 숫자 : 처음 발생시킬 시작 값 지정, 기본값 1
-- INCREMENT BY : 다음 값에 대한 증가치, 기본값1
-- MINVALUE : 발생시킬 최소값 지정
-- MAXVALUE : 발생시킬 최대값 지정
-- CYCLE/NOCYCLE : 시퀀스 값이 최대값까지 증가를 완료하면 CYCLE은 START WITH로 NOCYCLE은 에러 발생
-- CACHE/NOCACHE : 메모리상에서 시퀀스값을 관리, 기본값 20, 시퀀스 객체의 접근빈도를 줄여서 효율적인 운영 가능,

CREATE TABLE KH_SEQUENCE_TBL
(
  NO NUMBER PRIMARY KEY,
  NAME VARCHAR2(20) NOT NULL,
  AGE NUMBER NOT NULL
);
DESC KH_SEQUENCE TBL;

INSERT INTO KH_SEQUENCE_TBL VALUES(1, '시퀀스1', '11');
INSERT INTO KH_SEQUENCE_TBL VALUES(2, '시퀀스2', '22');
INSERT INTO KH_SEQUENCE_TBL VALUES(3, '시퀀스3', '33');
SELECT * FROM KH_SEQUENCE_TBL;
DELETE FROM KH_SEQUENCE_TBL WHERE NO = 3;
ROLLBACK;

CREATE SEQUENCE SEQ_KH_SNO;
INSERT INTO KH_SEQUENCE_TBL VALUES(SEQ_KH_SNO.NEXTVAL, '일용자', '11');
-- 1 행 이(가) 삽입되었습니다
SELECT * FROM KH_SEQUENCE_TBL;

INSERT INTO KH_SEQUENCE_TBL VALUES(SEQ_KH_SNO.NEXTVAL, '이용자', '22');
INSERT INTO KH_SEQUENCE_TBL VALUES(SEQ_KH_SNO.NEXTVAL, '삼용자', '33');
DELETE FROM KH_SEQUENCE_TBL WHERE NO = 2;
INSERT INTO KH_SEQUENCE_TBL VALUES(SEQ_KH_SNO.NEXTVAL, '사용자', '44');
SELECT SEQ_KH_SNO.NEXTVAL FROM DUAL; -- 시퀀스 START 및 증가
SELECT SEQ_KH_SNO.CURRVAL FROM DUAL; -- 현재 시퀀스값 증가시키지 않고 확인
INSERT INTO KH_SEQUENCE_TBL VALUES(SEQ_KH_SNO.NEXTVAL, '오용자', '55');
INSERT INTO KH_SEQUENCE_TBL VALUES(SEQ_KH_SNO.NEXTVAL, '육용자', '66');


DROP TABLE KH_SEQUENCE_TBL;
DROP SEQUENCE SEQ_KH_SNO; -- 시퀀스 삭제
CREATE SEQUENCE SEQ_KH_SNO; -- 시퀀스 생성
SELECT SEQ_KH_SNO.NEXTVAL FROM DUAL; -- 시퀀스 START 및 증가
SELECT SEQ_KH_SNO.CURRVAL FROM DUAL; -- 현재 시퀀스값 증가시키지 않고 확인
SELECT * FROM KH_SEQUENCE_TBL;










