SET SERVEROUTPUT ON;

-- ==================================== 오라클 인덱스 실습 ====================================
-- 1. 100만개의 데이터를 넣을 테이블생성
DROP TABLE KH_CUSTOMER_TBL;
DELETE FROM KH_CUSTOMER_TBL;
CREATE TABLE KH_CUSTOMER_TBL
(
  USER_ID VARCHAR2(20),
  USER_PW VARCHAR2(30),
  USER_NAME VARCHAR2(30),
  USER_PHONE VARCHAR2(30),
  USER_ADDR VARCHAR2(500),
  REG_DATE TIMESTAMP DEFAULT SYSTIMESTAMP, -- 시분초중요하면 TIMESTAMP (영화예매,구독권)
  MOD_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE SEQUENCE SEQ_CUSTOMER_TBL_USERID
MINVALUE 1 
MAXVALUE 999999999
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

DESC KH_CUSTOMER_TBL;
DECLARE
  V_USERID VARCHAR2(100);
BEGIN
  FOR N IN 1..1000000
  LOOP
    V_USERID := '1'||LPAD(SEQ_CUSTOMER_TBL_USERID.NEXTVAL,9,'0');
    INSERT INTO KH_CUSTOMER_TBL
    VALUES(V_USERID, '0000', N||'용자', '010-0000-'||V_USERID,
    '서울시 중구 명동'||V_USERID, DEFAULT, DEFAULT);
  END LOOP;
  COMMIT;
END;
/

SELECT COUNT(*) FROM KH_CUSTOMER_TBL ORDER BY 1 DESC;
-- 인덱스 성능 테스트
EXPLAIN PLAN FOR
SELECT COUNT(*) FROM KH_CUSTOMER_TBL WHERE USER_NAME LIKE '22%용자';
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
-- 인덱스 생성하기
CREATE INDEX IDX_CUSTOMER_USERNAME ON KH_CUSTOMER_TBL(USER_NAME);
-- 성능 테스트 해보기
EXPLAIN PLAN FOR
SELECT COUNT(*) FROM KH_CUSTOMER_TBL WHERE USER_NAME LIKE '22%용자';
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
-- SET AUTOTRACE ON, 오라클 튜닝할때 기본적으로 씀.










































