-- 제약조건 실습
-- 테이블 생성 (DDL - CREATE, ALTER, DROP)
CREATE TABLE USER_NO_CONSTRAINT (
  USER_NO NUMBER,
  USER_ID VARCHAR2(20),
  USER_PWD VARCHAR2(30),
  USER_NAME VARCHAR2(30),
  USER_GENDER VARCHAR2(10),
  USER_PHONE VARCHAR2(30),
  USER_EMAIL VARCHAR2(50)
);

-- 데이터 추가
INSERT INTO USER_NO_CONSTRAINT VALUES(1, 'khuser01', 'pass01', '일용자', '남', '01098774090', 'khuser01@iei.or.kr');
-- 데이터 조회
SELECT * FROM USER_NO_CONSTRAINT;
COMMIT;
INSERT INTO USER_NO_CONSTRAINT VALUES(2, 'khuser02', 'pass02','이용자','남','01098774090','khuser01@iei.or.kr');
INSERT INTO USER_NO_CONSTRAINT VALUES(3, null, null, null,'남','01098774090','khuser01@iei.or.kr');

-- 테이블생성 (DDL -- CREATE, ALTER, DROP)
CREATE TABLE USER_CONSTRAINT (
  USER_NO NUMBER,
  USER_ID VARCHAR2(20) NOT NULL,
  USER_PWD VARCHAR2(30) NOT NULL,
  USER_NAME VARCHAR2(30) NOT NULL,
  USER_GENDER VARCHAR2(10),
  USER_PHONE VARCHAR2(30),
  USER_EMAIL VARCHAR2(50)
);
-- 데이터 조회
SELECT * FROM USER_CONSTRAINT;
-- 데이터 추가
INSERT INTO USER_CONSTRAINT VALUES(1,'khuser01', 'pass01', '일용자', '남', '01098774090', 'khuser01@naver.com');
INSERT INTO USER_CONSTRAINT VALUES(2, null, null, null, '남', '01098774090', 'khuser01@naver.com');

























