SELECT * FROM TB_CLASS;
SELECT * FROM TB_CLASS_PROFESSOR;

--1번문제
SELECT DEPARTMENT_NAME AS "학과 명",CATEGORY AS 계열 FROM TB_DEPARTMENT
GROUP BY DEPARTMENT_NAME ,CATEGORY ORDER BY 2;


--2번문제
SELECT DEPARTMENT_NAME ||'의 정원은 ' ||CAPACITY ||'명 입니다.'
FROM TB_DEPARTMENT
GROUP BY DEPARTMENT_NAME,CAPACITY ORDER BY 1;

--6번문제
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

--Additional SELECT 1번
SELECT STUDENT_NO AS 학번 , STUDENT_NAME AS 이름 , TO_CHAR(ENTRANCE_DATE,'RRRR-MM-DD') AS 입학년도

FROM TB_STUDENT
WHERE DEPARTMENT_NO LIKE '002'
ORDER BY 3;

--Additional SELECT 6번
SELECT TO_CHAR(TO_DATE('2020-12-25','YYYY-MM-DD'),'DAY')FROM DUAL;
--답은 금요일

--Additional 11번
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

--Additional SELECT - Option 1번
SELECT STUDENT_NAME AS "학생 이름",STUDENT_ADDRESS AS 주소지
FROM TB_STUDENT ORDER BY 1;

--Additional SELECT - Option 6번
SELECT STUDENT_NO AS 학생번호, STUDENT_NAME AS 이름 
, DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT ON  TB_STUDENT.DEPARTMENT_NO = TB_DEPARTMENT.DEPARTMENT_NO ORDER BY 2;

-- Additional SELECT - Option 11번
SELECT DEPARTMENT_NAME, STUDENT_NAME,PROFESSOR_NAME
FROM TB_STUDENT
JOIN TB_PROFESSOR ON COACH_PROFESSOR_NO = PROFESSOR_NO
JOIN TB_DEPARTMENT ON TB_STUDENT.DEPARTMENT_NO = TB_DEPARTMENT.DEPARTMENT_NO
WHERE STUDENT_NO ='A313047';

-- Additional SELECT - Option 16번
SELECT TB_CLASS.CLASS_NO, TB_CLASS.CLASS_NAME, AVG(POINT)
FROM TB_CLASS 
JOIN TB_DEPARTMENT ON TB_CLASS.DEPARTMENT_NO = TB_DEPARTMENT.DEPARTMENT_NO
JOIN TB_GRADE ON TB_CLASS.CLASS_NO = TB_CLASS.CLASS_NO
WHERE TB_CLASS.DEPARTMENT_NO = '034' AND TB_CLASS.CLASS_NO NOT LIKE 'C073%'
group by TB_CLASS.CLASS_NO, TB_CLASS.CLASS_NAME order by 1;


--DDL 1번

CREATE TABLE TB_CATEGORY (
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);
DESC TB_CATEGORY;
--DDL 6번

ALTER TABLE TB_CATEGORY RENAME COLUMN NAME TO CATEGORY_NAME;
ALTER TABLE TB_CATEGORY RENAME COLUMN USE_YN TO CATEGORY_USE_YN;


-- DML 1번

INSERT INTO TB_CLASS_TYPE VALUES ('01','전공필수');
INSERT INTO TB_CLASS_TYPE VALUES ('02','전공선택');
INSERT INTO TB_CLASS_TYPE VALUES ('03','교양필수');
INSERT INTO TB_CLASS_TYPE VALUES ('04','교양선택');
INSERT INTO TB_CLASS_TYPE VALUES ('05','논문지도');


-- DML 6번
SELECT SUBSTR(STUDENT_SSN,1,6)
FROM TB_STUDENT;