CREATE USER CHUN_UNIVERSITY IDENTIFIED BY CHUN;
GRANT CONNECT, RESOURCE TO CHUN_UNIVERSITY

-- 비밀번호 변경!
ALTER USER CHUN_UNIVERSITY IDENTIFIED BY CHUN;

--User CHUN_UNIVERSITY이(가) 생성되었습니다.
--Grant을(를) 성공했습니다.