-- ========= 새로운 ROLE 만들기 (정리용) =========
CREATE ROLE VIEWRESOURCE;
GRANT CREATE VIEW TO VIEWRESOURCE;
GRANT SELECT ON KHUSER01.COFFEE TO VIEWRESOURCE;


SHOW USER;
CREATE ROLE VIEWRESOURCE; --Role VIEWRESOURCE이(가) 생성되었습니다.
GRANT CREATE VIEW TO VIEWRESOURCE;
GRANT SELECT ON KHUSER01.COFFEE TO VIEWRESOURCE;

--ROLE에 부연된권한확인
-- VIEWRESOURCE 라는 ROLE에 CREATE VIEW가 있다.
SELECT * FROM DBA_SYS_PRIVS
WHERE GRANTEE = 'VIEWRESOURCE';












